import Foundation

/// BERT WordPiece tokenizer, a faithful port of Hugging Face's
/// `BasicTokenizer` + `WordpieceTokenizer` pair (`tokenization_bert.py`).
///
/// It exists because the Core ML embedder needs token ids and macOS ships no
/// WordPiece implementation. Parity with the Python tokenizer is checked
/// against fixtures generated by `Tools/embedder/convert.py`
/// (`out/<name>.golden.json`).
///
/// The pipeline, in order:
/// 1. drop NUL/replacement/control characters, fold every whitespace run to `" "`;
/// 2. pad CJK ideographs with spaces so each becomes its own token;
/// 3. split on whitespace;
/// 4. lowercase and strip accents (when the vocabulary is uncased);
/// 5. split punctuation into standalone tokens;
/// 6. greedy longest-match-first WordPiece against the vocabulary;
/// 7. wrap in `[CLS] … [SEP]`, truncating the middle to `maxLength`.
///
/// All indexing is by Unicode scalar (Python code points), not by grapheme
/// cluster, which is what keeps combining marks and emoji aligned with the
/// reference implementation.
public struct WordPieceTokenizer: Sendable {
    /// Knobs that mirror `tokenizer_config.json`.
    public struct Configuration: Sendable {
        public var lowercase: Bool
        /// `nil` follows `lowercase`, matching Hugging Face's default.
        public var stripAccents: Bool?
        public var maxInputCharsPerWord: Int
        public var unknownToken: String
        public var classToken: String
        public var separatorToken: String
        public var padToken: String
        public var continuingSubwordPrefix: String

        public init(
            lowercase: Bool = true,
            stripAccents: Bool? = nil,
            maxInputCharsPerWord: Int = 100,
            unknownToken: String = "[UNK]",
            classToken: String = "[CLS]",
            separatorToken: String = "[SEP]",
            padToken: String = "[PAD]",
            continuingSubwordPrefix: String = "##"
        ) {
            self.lowercase = lowercase
            self.stripAccents = stripAccents
            self.maxInputCharsPerWord = maxInputCharsPerWord
            self.unknownToken = unknownToken
            self.classToken = classToken
            self.separatorToken = separatorToken
            self.padToken = padToken
            self.continuingSubwordPrefix = continuingSubwordPrefix
        }

        /// `true` when accents should be removed for this configuration.
        public var stripsAccents: Bool { stripAccents ?? lowercase }
    }

    /// One tokenized input, already padded to the model's fixed sequence length.
    public struct Encoding: Sendable, Equatable {
        /// Token ids including `[CLS]`/`[SEP]` and `[PAD]` filler.
        public var ids: [Int32]
        /// `1` for real tokens, `0` for padding.
        public var attentionMask: [Int32]
        /// Number of non-padding tokens (`[CLS]`/`[SEP]` included).
        public var tokenCount: Int
        /// `true` when the input did not fit and was cut at `maxLength`.
        public var truncated: Bool
    }

    public enum LoadError: Error, CustomStringConvertible {
        case vocabularyUnreadable(URL)
        case missingSpecialToken(String)

        public var description: String {
            switch self {
            case let .vocabularyUnreadable(url): "cannot read vocab.txt at \(url.path)"
            case let .missingSpecialToken(token): "vocabulary is missing \(token)"
            }
        }
    }

    public let configuration: Configuration
    private let vocabulary: [String: Int32]
    private let unknownID: Int32
    private let classID: Int32
    private let separatorID: Int32
    /// Id used for padding; `attentionMask` is what actually masks it out.
    public let padID: Int32

    public var vocabularySize: Int { vocabulary.count }

    /// Builds a tokenizer from an in-memory vocabulary (token → id).
    public init(vocabulary: [String: Int32], configuration: Configuration = .init()) throws {
        func require(_ token: String) throws -> Int32 {
            guard let id = vocabulary[token] else { throw LoadError.missingSpecialToken(token) }
            return id
        }
        self.vocabulary = vocabulary
        self.configuration = configuration
        unknownID = try require(configuration.unknownToken)
        classID = try require(configuration.classToken)
        separatorID = try require(configuration.separatorToken)
        padID = try require(configuration.padToken)
    }

    /// Loads a `vocab.txt` — one token per line, line number is the id.
    public init(vocabularyAt url: URL, configuration: Configuration = .init()) throws {
        guard let text = try? String(contentsOf: url, encoding: .utf8) else {
            throw LoadError.vocabularyUnreadable(url)
        }
        var vocabulary: [String: Int32] = [:]
        vocabulary.reserveCapacity(32_768)
        var index: Int32 = 0
        for line in text.split(separator: "\n", omittingEmptySubsequences: false) {
            // vocab.txt is one raw token per line; a trailing \r or final empty
            // line is file noise, not a token.
            var token = Substring(line)
            if token.hasSuffix("\r") { token = token.dropLast() }
            if token.isEmpty, index > 0 || text.isEmpty { continue }
            vocabulary[String(token)] = index
            index += 1
        }
        try self.init(vocabulary: vocabulary, configuration: configuration)
    }

    // MARK: - Public API

    /// Tokenizes to strings, without the special tokens. Mostly for tests.
    public func tokenize(_ text: String) -> [String] {
        basicTokenize(text).flatMap(wordPiece(_:))
    }

    /// Ids for `text` without `[CLS]`/`[SEP]` or padding.
    public func encodeTokensOnly(_ text: String) -> [Int32] {
        tokenize(text).map { vocabulary[$0] ?? unknownID }
    }

    /// Full encoding for the model: `[CLS] … [SEP]`, truncated to `maxLength`
    /// and padded to it.
    public func encode(_ text: String, maxLength: Int) -> Encoding {
        precondition(maxLength >= 2, "maxLength must leave room for [CLS] and [SEP]")
        var ids = encodeTokensOnly(text)
        let truncated = ids.count > maxLength - 2
        if truncated { ids = Array(ids.prefix(maxLength - 2)) }

        var result = [Int32](repeating: padID, count: maxLength)
        var mask = [Int32](repeating: 0, count: maxLength)
        result[0] = classID
        mask[0] = 1
        for (offset, id) in ids.enumerated() {
            result[offset + 1] = id
            mask[offset + 1] = 1
        }
        result[ids.count + 1] = separatorID
        mask[ids.count + 1] = 1
        return Encoding(
            ids: result, attentionMask: mask, tokenCount: ids.count + 2, truncated: truncated
        )
    }

    /// Number of tokens `text` occupies including `[CLS]`/`[SEP]`, ignoring
    /// truncation. Used by the chunker (M3-02) to size chunks.
    public func tokenCount(_ text: String) -> Int {
        tokenize(text).count + 2
    }

    // MARK: - Stage 1–5: basic tokenization

    private func basicTokenize(_ text: String) -> [String] {
        var cleaned = String.UnicodeScalarView()
        for scalar in text.unicodeScalars {
            if scalar.value == 0 || scalar.value == 0xFFFD || Self.isControl(scalar) { continue }
            if Self.isWhitespace(scalar) {
                cleaned.append(" ")
            } else if Self.isCJK(scalar) {
                cleaned.append(" ")
                cleaned.append(scalar)
                cleaned.append(" ")
            } else {
                cleaned.append(scalar)
            }
        }

        var tokens: [String] = []
        for word in String(cleaned).split(separator: " ", omittingEmptySubsequences: true) {
            var scalars = Array(word.unicodeScalars)
            if configuration.lowercase {
                scalars = Array(String(String.UnicodeScalarView(scalars)).lowercased().unicodeScalars)
            }
            if configuration.stripsAccents {
                scalars = Self.stripAccents(scalars)
            }
            tokens.append(contentsOf: Self.splitPunctuation(scalars))
        }
        return tokens
    }

    private static func stripAccents(_ scalars: [Unicode.Scalar]) -> [Unicode.Scalar] {
        let decomposed = String(String.UnicodeScalarView(scalars)).decomposedStringWithCanonicalMapping
        return decomposed.unicodeScalars.filter { $0.properties.generalCategory != .nonspacingMark }
    }

    private static func splitPunctuation(_ scalars: [Unicode.Scalar]) -> [String] {
        var output: [String] = []
        var current = String.UnicodeScalarView()
        for scalar in scalars {
            if isPunctuation(scalar) {
                if !current.isEmpty {
                    output.append(String(current))
                    current = String.UnicodeScalarView()
                }
                output.append(String(scalar))
            } else {
                current.append(scalar)
            }
        }
        if !current.isEmpty { output.append(String(current)) }
        return output
    }

    // MARK: - Stage 6: WordPiece

    private func wordPiece(_ token: String) -> [String] {
        let scalars = Array(token.unicodeScalars)
        if scalars.count > configuration.maxInputCharsPerWord {
            return [configuration.unknownToken]
        }
        var subTokens: [String] = []
        var start = 0
        while start < scalars.count {
            var end = scalars.count
            var match: String?
            while start < end {
                var candidate = String(String.UnicodeScalarView(scalars[start ..< end]))
                if start > 0 { candidate = configuration.continuingSubwordPrefix + candidate }
                if vocabulary[candidate] != nil {
                    match = candidate
                    break
                }
                end -= 1
            }
            guard let match else { return [configuration.unknownToken] }
            subTokens.append(match)
            start = end
        }
        return subTokens
    }

    // MARK: - Character classes (BERT's definitions, not Foundation's)

    static func isWhitespace(_ scalar: Unicode.Scalar) -> Bool {
        switch scalar.value {
        case 0x20, 0x09, 0x0A, 0x0D: return true
        default: return scalar.properties.generalCategory == .spaceSeparator
        }
    }

    static func isControl(_ scalar: Unicode.Scalar) -> Bool {
        // \t \n \r are whitespace for BERT even though Unicode calls them control.
        switch scalar.value {
        case 0x09, 0x0A, 0x0D: return false
        default:
            switch scalar.properties.generalCategory {
            case .control, .format, .lineSeparator, .paragraphSeparator, .privateUse, .surrogate:
                return true
            default:
                return false
            }
        }
    }

    static func isPunctuation(_ scalar: Unicode.Scalar) -> Bool {
        let value = scalar.value
        // BERT treats every non-alphanumeric ASCII character as punctuation,
        // including `$`, `+`, `<`, `|`, `~` — which Unicode files under Symbol.
        if (33 ... 47).contains(value) || (58 ... 64).contains(value)
            || (91 ... 96).contains(value) || (123 ... 126).contains(value) {
            return true
        }
        switch scalar.properties.generalCategory {
        case .connectorPunctuation, .dashPunctuation, .openPunctuation, .closePunctuation,
             .initialPunctuation, .finalPunctuation, .otherPunctuation:
            return true
        default:
            return false
        }
    }

    static func isCJK(_ scalar: Unicode.Scalar) -> Bool {
        switch scalar.value {
        case 0x4E00 ... 0x9FFF, 0x3400 ... 0x4DBF, 0x20000 ... 0x2A6DF, 0x2A700 ... 0x2B73F,
             0x2B740 ... 0x2B81F, 0x2B820 ... 0x2CEAF, 0xF900 ... 0xFAFF, 0x2F800 ... 0x2FA1F:
            return true
        default:
            return false
        }
    }
}
